import { Label } from "@radix-ui/react-label";

export const countries = [
    { value: "argentina", label: "Argentina" },
    { value: "bolivia", label: "Bolivia" },
    { value: "brazil", label: "Brazil" },
    { value: "chile", label: "Chile" },
    { value: "colombia", label: "Colombia" },
    { value: "costa_rica", label: "Costa Rica" },
    { value: "cuba", label: "Cuba" },
    { value: "dominican republic", label: "República Dominicana" },
    { value: "ecuador", label: "Ecuador" },
    { value: "el salvador", label: "El Salvador" },
    { value: "guatemala", label: "Guatemala" },
    { value: "honduras", label: "Honduras" },
    { value: "mexico", label: "México" },
    { value: "nicaragua", label: "Nicaragua" },
    { value: "panama", label: "Panamá" },
    { value: "paraguay", label: "Paraguay" },
    { value: "peru", label: "Perú" },
    { value: "uruguay", label: "Uruguay" },
    { value: "venezuela", label: "Venezuela" },
    { value: "spain", label: "España" },
    { value: "portugal", label: "Portugal" },
    { value: "estados unidos", label: "Estados Unidos" },
    { value: "canada", label: "Canadá" },
    { value: "germany", label: "Alemania" },
    { value: "france", label: "Francia" },
    { value: "italy", label: "Italia" },
    { value: "uk", label: "Reino Unido" },
    { value: "china", label: "China" },
    { value: "japan", label: "Japón" },
    { value: "india", label: "India" },
    { value: "australia", label: "Australia" },
    { value: "puerto rico", label: "Puerto Rico" },
    { value:"holanda", label: "Holanda"}
]; 